CREATE TABLE IF NOT EXISTS PRICES(
    ID UUID DEFAULT RANDOM_UUID() NOT NULL,
    BRAND_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PRICE_LIST INT NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    CURRENCY VARCHAR (3) NOT NULL,
    CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);